### ISSUE TITLE
Convert from default bibitem to amsbib format 

### ISSUE THREAD

**Issue by mesenev** [SergejZnamenskij/amsbib#1]
Are there any known solutions? Except manual one.

**Comment by SergejZnamenskij** [comment]
Unfortunately, no known solution. It seems hard to be possible.

**Comment by SergejZnamenskij** [comment]
The tho formats have different keys. Thought for most simple and usual standard items (papers in journals, monographs, and proceeding papers) some kind of any side converter seems to be possible, but there are a lot of less simple items without clear unambiguous correspondence.
